#!/usr/bin/env bash

###############################################################################
# Checking if the user has the required installs , mostly for added 'coolness'
###############################################################################

pwd

## declare an array variable
declare -a arr=("toilet" "figlet" "fortune" "yes" "dos2unix")

## now loop through the above array
for i in "${arr[@]}"
do
   echo "$i"
   ./src/scripts/installer $i
   # or do whatever with individual element of the array
done
