#!/usr/bin/env bash

Menu="REPO MENU"
Menu1="Show repositories"
Menu2="Edit repositories"

function show_header(){
	#feed the narcistic beast
  src/scripts/show-logo $Menu
}

function show_menu(){
	echo "   1. $Menu1"
	echo "   2. $Menu2"
	echo ''
}

function show_repos(){
  echo "Showing the repositories.."
  while IFS='' read -r line || [[ -n "$line" ]]; do
  str=""
  IFS=', ' read -r -a array <<< "$line"
  REPO_NAME="${array[0]}"
  REPO_LINK="${array[1]}"

  # if length of string is short add a tab
  size=${#REPO_NAME}
  size=$(( size + 0 ))
  if [[ $size -gt 17 ]]; then
      tab="\t"
  else
      tab="\t\t"
  fi

  echo -e "$REPO_NAME $tab $REPO_LINK"
  #skip the header
  #   if [[ $app != "APP" ]]
  #   then
  #     #Checking for apps to update
  #       if [ -d $repo"/" ]; then
  #         # Control will enter here if $DIRECTORY exists.
  #         cd $repo
  #         sudo git fetch origin 'refs/tags/*:refs/tags/*'
  #         if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
  #             echo -e "$app , OK" >> $log_file
  #             git checkout tags/$tag
  #             # act according to the app
  #             #app_actions
  #         else
  #             echo -e "$app , NOK" >> $log_file
  #         fi
  #         cd $build_folder
  #     else
  #       cd $build_folder
  #           echo -e "$app , NOK" >> $log_file
  #     fi
  # fi

done < src/data/repos


}

function edit_repos(){
  echo "Editing the repositories"

}

#intro
show_header
show_menu

#do your thing based on menu choice
printf 'Make your choice : '
read -r choice

show_header


if [ $choice == 1 ] ; then
	Menu=$Menu1
	show_header
	show_repos
elif [ $choice == 2 ] ; then
	Menu=$Menu2
	show_header
	edit_repos
else
	echo "You haven't made a valid choice"
fi
