#!/usr/bin/env bash

Menu="REPO MENU"
Menu1="Show repositories"
Menu2="Edit repositories file"
Menu3="Add a repository"

bHandle=False

# FUNCTIONS ###################################################################

function show_header(){
	#feed the narcistic beast
  src/scripts/show-logo $Menu
}

function show_menu(){
	echo "   1. $Menu1"
	echo "   2. $Menu2"
	echo "   3. $Menu3"
	echo ''
}

function show_repos(){
  i=0
  while IFS='' read -r line || [[ -n "$line" ]]; do
    str=""
    IFS=', ' read -r -a array <<< "$line"
    REPO_NAME="${array[0]}"
    REPO_LINK="${array[1]}"

    # output the list
      printf "%-4s %-20s %s\n" "$i" $REPO_NAME $REPO_LINK

    i=$((i+1))
  done < src/data/repos
}

function edit_repos(){
  nano src/data/repos
}

function add_repo(){
  printf 'The name of the new repo : '
  read -r REPO_NAME
  printf 'The link to the new repo : '
  read -r REPO_LINK
  echo "$REPO_NAME,$REPO_LINK" >> src/data/repos
  echo "Added the new repo to the list"
  echo "Showing the new list : "
	show_repos
}

# SCRIPT ###################################################################

#intro
show_header
show_menu

#do your thing based on menu choice
printf 'Make your choice : '
read -r choice

show_header


if [ $choice == 1 ] ; then
	Menu=$Menu1
	show_header
	show_repos
elif [ $choice == 2 ] ; then
	Menu=$Menu2
	show_header
	edit_repos
elif [ $choice == 3 ] ; then
	Menu=$Menu3
	show_header
	add_repo
else
	echo "You haven't made a valid choice"
fi

src/scripts/menu-return
